version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=quiz_site
      - POSTGRES_USER=quiz_site
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ=UTC
    ports:
      - 127.0.0.1:5432:5432
    tmpfs:
      - /var/lib/postgresql/data

  # migration:
  #   build: .
  #   command: 'npm run migrate'
  #   volumes:
  #     - .:/usr/app/
  #     - /usr/app/node_modules
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - postgres
